export const MEDICAMENT_LIST_REQUEST = 'MEDICAMENT_LIST_REQUEST';
export const MEDICAMENT_LIST_SUCCESS = 'MEDICAMENT_LIST_SUCCESS';
export const MEDICAMENT_LIST_FAIL = 'MEDICAMENT_LIST_FAIL';

export const MEDICAMENT_DETAILS_REQUEST = 'MEDICAMENT_DETAILS_REQUEST';
export const MEDICAMENT_DETAILS_SUCCESS = 'MEDICAMENT_DETAILS_SUCCESS';
export const MEDICAMENT_DETAILS_FAIL = 'MEDICAMENT_DETAILS_FAIL';

export const MEDICAMENT_SAVE_REQUEST = 'MEDICAMENT_SAVE_REQUEST';
export const MEDICAMENT_SAVE_SUCCESS = 'MEDICAMENT_SAVE_SUCCESS';
export const MEDICAMENT_SAVE_FAIL = 'MEDICAMENT_SAVE_FAIL';

export const MEDICAMENT_SEARCH_REQUEST = 'MEDICAMENT_SEARCH_REQUEST';
export const MEDICAMENT_SEARCH_SUCCESS = 'MEDICAMENT_SEARCH_SUCCESS';
export const MEDICAMENT_SEARCH_FAIL = 'MEDICAMENT_SEARCH_FAIL';

export const LIST_MEDICAMENT_REQUEST = 'LIST_MEDICAMENT_REQUEST';
export const LIST_MEDICAMENT_SUCCESS = 'LIST_MEDICAMENT_SUCCESS';
export const LIST_MEDICAMENT_FAIL = 'LIST_MEDICAMENT_FAIL';

export const MEDICAMENT_DELETE_REQUEST = 'MEDICAMENT_DELETE_REQUEST';
export const MEDICAMENT_DELETE_SUCCESS = 'MEDICAMENT_DELETE_SUCCESS';
export const MEDICAMENT_DELETE_FAIL = 'MEDICAMENT_DELETE_FAIL';