export const PANIER_ADD_ITEM = 'PANIER_ADD_ITEM';
export const PANIER_REMOVE_ITEM = 'PANIER_REMOVE_ITEM';

export const PANIER_CONFIRM_ITEM = 'PANIER_CONFIRM_ITEM';

export const PANIER_RESERV_ITEM = 'PANIER_RESERV_ITEM';