export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const PHARM_REGISTER_REQUEST = 'PHARM_REGISTER_REQUEST';
export const PHARM_REGISTER_SUCCESS = 'PHARM_REGISTER_SUCCESS';
export const PHARM_REGISTER_FAIL = 'PHARM_REGISTER_FAIL';

export const PROFIL_SHOW_ACHAT = 'PROFIL_SHOW_ACHAT';

export const PROFIL_SHOW_RESERV = 'PROFIL_SHOW_RESERV';

export const MEDICAMENT_CANCEL_REQUEST = 'MEDICAMENT_CANCEL_REQUEST';
export const MEDICAMENT_CANCEL_SUCCESS = 'MEDICAMENT_CANCEL_SUCCESS';
export const MEDICAMENT_CANCEL_FAIL = 'MEDICAMENT_CANCEL_FAIL';

export const MEDICAMENT_CONFIRM_REQUEST = 'MEDICAMENT_CONFIRM_REQUEST';
export const MEDICAMENT_CONFIRM_SUCCESS = 'MEDICAMENT_CONFIRM_SUCCESS';
export const MEDICAMENT_CONFIRM_FAIL = 'MEDICAMENT_CONFIRM_FAIL';

export const PHARM_SHOW_ACHATFINAL = 'PHARM_SHOW_ACHATFINAL';

export const PHARM_SHOW_ACHAT = 'PHARM_SHOW_ACHAT';

export const PHARM_SHOW_RESERV = 'PHARM_SHOW_RESERV';

export const USER_SIGNOUT = 'USER_SIGNOUT';