export const VILLE_LIST_REQUEST = 'VILLE_LIST_REQUEST';
export const VILLE_LIST_SUCCESS = 'VILLE_LIST_SUCCESS';
export const VILLE_LIST_FAIL = 'VILLE_LIST_FAIL';

export const POSITION_LIST_REQUEST = 'POSITION_LIST_REQUEST';
export const POSITION_LIST_SUCCESS = 'POSITION_LIST_SUCCESS';
export const POSITION_LIST_FAIL = 'POSITION_LIST_FAIL';